apiVersion: v1
kind: Secret
metadata:
  name: fence-creds
type: Opaque
stringData:
  creds.json: |-
      {
        "db_host": "{{ .Values.database.host }}",
        "db_username": "{{ .Values.database.user }}",
        "db_password": "{{ .Values.database.password }}",
        "db_database": "{{ .Values.database.dbname }}",
        "hostname": "{{ .Values.hostname }}",
        "indexd_password": "",
        "google_client_secret": "YOUR.GOOGLE.SECRET",
        "google_client_id": "YOUR.GOOGLE.CLIENT",
        "hmac_key": ""
      }

