apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deployment
spec:
  selector:
    matchLabels:
      {{- include "portal.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.strategy | nindent 8 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "portal.labels" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken}}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}      
      containers:
        - name: portal
          image: "quay.io/cdis/data-portal:3.30.0"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /portal/
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /portal/
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: 80
            - containerPort: 443
          command:
            - /bin/bash
            - ./dockerStart.sh
          env:
            {{- toYaml .Values.env | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      
