apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deployment
spec:
  selector:
    matchLabels:
      {{- include "portal.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.strategy | nindent 8 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "portal.labels" . | nindent 8 }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken}}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}      
      containers:
        - name: portal
          image: "quay.io/cdis/data-portal:3.30.0"
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /portal/
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /portal/
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
            # TODO: re-add resources
          ports:
            - containerPort: 80
            - containerPort: 443
          command:
            - /bin/bash
            - ./dockerStart.sh
          env:
            - name: HOSTNAME
              value: revproxy-service
            # disable npm 7's brand new update notifier to prevent Portal from stuck at starting up
            # see https://github.com/npm/cli/issues/3163
            - name: NPM_CONFIG_UPDATE_NOTIFIER
              value: "false"

            {{- with .Values.portalApp  }}
            - name: APP
              value: {{ . }}
            {{- end }}
            - name: GEN3_BUNDLE
              value: ""
            {{- with .Values.logoutInactiveUsers  }}
            - name: LOGOUT_INACTIVE_USERS
              value: {{ . }}
            {{- end }}
            {{- with .Values.workspaceTimeoutMinutes  }}
            - name: WORKSPACE_TIMEOUT_IN_MINUTES
              value: {{ . }}
            {{- end }}
            {{- with .Values.tierAccessLevel  }}
            - name: TIER_ACCESS_LEVEL
              ## acceptable values for `tier_access_level` are: `libre`, `regular` and `private`. If omitted, by default common will be treated as `private`
              value: {{ . }}
            {{- end }}
            {{- with .Values.tierAccessLimit  }}
            - name: TIER_ACCESS_LIMIT
              value: {{ . }}
            {{- end }}
            {{- with .Values.fenceUrl  }}
            - name: FENCE_URL
              value: {{ . }}
            {{- end }}
            {{- with .Values.indexdUrl  }}
            - name: INDEXD_URL
              value: {{ . }}
            {{- end }}
            {{- with .Values.workspaceUrl  }}
            - name: WORKSPACE_URL
              value: {{ . }}
            {{- end }}
            {{- with .Values.manifestServiceUrl  }}
            - name: MANIFEST_SERVICE_URL
              value: {{ . }}
            {{- end }}
            {{- with .Values.wtsUrl  }}
            - name: WTS_URL
              value: {{ . }}
            {{- end }}
            {{- with .Values.privacyPolicyUrl  }}
            - name: PRIVACY_POLICY_URL
              value: {{ . }}
            {{- end }}
            {{- with .Values.mapboxApiToken  }}
            - name: MAPBOX_API_TOKEN
              value: {{ . }}
            {{- end }}

            {{- with .Values.datadogApplicationId  }}      
            - name: DATADOG_APPLICATION_ID
              # Optional client token for Datadog
              value: {{ . }}
            {{- end }}
            {{- with .Values.datadogClientToken  }}      
            - name: DATADOG_CLIENT_TOKEN
              # Optional client token for Datadog
              value: {{ . }}
            {{- end }}
            {{- with .Values.dataUploadBucket  }}
            - name: DATA_UPLOAD_BUCKET
              value: {{ . }}
            {{- end }}
              # S3 bucket name for data upload, for setting up CSP
              #GEN3_DATA_UPLOAD_BUCKET|-value: ""-|
            - name: BASENAME
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      
